# Generated by Django 6.0.4 on 2026-04-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=1, help_text='Display order (lower numbers - zero included - appear first).')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time last updated.')),
                ('type', models.CharField(choices=[('short', 'Short Description'), ('long', 'Long Description'), ('mission_statement', 'Mission Statement'), ('vision_statement', 'Vision Statement')], help_text='Select the description type. Each type can only be added once.', max_length=20, unique=True)),
                ('value', models.TextField(blank=True, help_text='Enter the description for your organization/business/company.')),
            ],
            options={
                'ordering': ['display_order', 'type'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=1, help_text='Display order (lower numbers - zero included - appear first).')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time last updated.')),
                ('image', models.ImageField(blank=True, help_text='Upload an image file.', null=True, upload_to='base/images/')),
                ('image_alt', models.CharField(blank=True, help_text='Alternative text for accessibility.', max_length=255)),
                ('name', models.CharField(choices=[('favicon_ico', 'Favicon (.ico)'), ('favicon_svg', 'Favicon (.svg)'), ('apple_touch_icon', 'Apple Touch Icon')], help_text='Select the icon type. Each type can only be added once.', max_length=20, unique=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=1, help_text='Display order (lower numbers - zero included - appear first).')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time last updated.')),
                ('image', models.ImageField(blank=True, help_text='Upload an image file.', null=True, upload_to='base/images/')),
                ('image_alt', models.CharField(blank=True, help_text='Alternative text for accessibility.', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this item should be treated as active. Unselect this instead of deleting items.')),
                ('is_primary', models.BooleanField(default=False, help_text='Designates whether this item is the primary or default item. Only one active item should be marked as primary.')),
                ('name', models.CharField(choices=[('light', 'Light Background'), ('dark', 'Dark Background'), ('colorless', 'Colorless Background')], help_text='Select the background variant this logo is optimised for. Each variant can only be added once.', max_length=20, unique=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=1, help_text='Display order (lower numbers - zero included - appear first).')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time last updated.')),
                ('type', models.CharField(choices=[('full_name', 'Full Name'), ('short_name', 'Short Name'), ('legal_name', 'Legal Name')], help_text='Select the name type. Each type can only be added once.', max_length=20, unique=True)),
                ('value', models.CharField(blank=True, help_text='Enter the brand name of your organization/business/company.', max_length=255)),
            ],
            options={
                'ordering': ['display_order', 'type'],
                'abstract': False,
            },
        ),
    ]
