# Generated by Django 6.0.4 on 2026-04-29 09:23

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=1, help_text='Display order (lower numbers - zero included - appear first).')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time last updated.')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this item should be treated as active. Unselect this instead of deleting items.')),
                ('is_primary', models.BooleanField(default=False, help_text='Designates whether this item is the primary or default item. Only one active item should be marked as primary.')),
                ('email', models.EmailField(help_text='Email address for public contact or form submissions (e.g., user@example.com).', max_length=254, unique=True)),
            ],
            options={
                'ordering': ['display_order', 'email'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=1, help_text='Display order (lower numbers - zero included - appear first).')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time last updated.')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this item should be treated as active. Unselect this instead of deleting items.')),
                ('is_primary', models.BooleanField(default=False, help_text='Designates whether this item is the primary or default item. Only one active item should be marked as primary.')),
                ('number', phonenumber_field.modelfields.PhoneNumberField(help_text='Phone number in Kenyan local or international format (e.g., 0712345678 or +254712345678).', max_length=128, region='KE', unique=True)),
            ],
            options={
                'ordering': ['display_order', 'number'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhysicalLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=1, help_text='Display order (lower numbers - zero included - appear first).')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time last updated.')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this item should be treated as active. Unselect this instead of deleting items.')),
                ('is_primary', models.BooleanField(default=False, help_text='Designates whether this item is the primary or default item. Only one active item should be marked as primary.')),
                ('name', models.CharField(help_text='Name for this location (e.g., Main Office).', max_length=100, unique=True)),
                ('building', models.CharField(blank=True, help_text='Building name, suite, or block (e.g., Britam Tower, Block A).', max_length=100)),
                ('street_address', models.CharField(blank=True, help_text='Street line including number and street name.', max_length=255)),
                ('city', models.CharField(blank=True, help_text='City, town, or locality.', max_length=100)),
                ('state_province', models.CharField(blank=True, help_text='State, province, county, or region.', max_length=100)),
                ('postal_code', models.CharField(blank=True, help_text='ZIP or postal code.', max_length=20)),
                ('country', models.CharField(blank=True, default='Kenya', help_text='Country name (defaults to Kenya).', max_length=100)),
                ('map_embed_url', models.URLField(blank=True, help_text='Embeddable map URL (for example, a Google Maps iframe source URL).', max_length=500)),
            ],
            options={
                'ordering': ['display_order', 'name', 'city'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=1, help_text='Display order (lower numbers - zero included - appear first).')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time last updated.')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this item should be treated as active. Unselect this instead of deleting items.')),
                ('is_primary', models.BooleanField(default=False, help_text='Designates whether this item is the primary or default item. Only one active item should be marked as primary.')),
                ('name', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'X (formerly Twitter)'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('pinterest', 'Pinterest'), ('snapchat', 'Snapchat'), ('discord', 'Discord'), ('telegram', 'Telegram'), ('github', 'GitHub'), ('reddit', 'Reddit'), ('twitch', 'Twitch')], help_text='Select the social platform. Each platform can only be added once.', max_length=20, unique=True)),
                ('icon', models.CharField(blank=True, editable=False, help_text='Bootstrap icon CSS classes, auto-generated from the selected platform.', max_length=50)),
                ('username', models.CharField(blank=True, help_text="Your handle or username on this platform (e.g. 'johndoe' or 'acme-corp'). Do not include the full URL — it is built automatically from the platform. For YouTube and TikTok the '@' prefix is added automatically if omitted.", max_length=255)),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'abstract': False,
            },
        ),
    ]
