# Generated by Django 6.0.4 on 2026-04-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bootstrap_icon', models.CharField(blank=True, help_text="Optional Bootstrap icon class. Example: 'bi bi-cart' for a shopping cart icon. Find icons at [Bootstrap Icons](https://icons.getbootstrap.com/).", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time last updated.')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this item should be treated as active. Unselect this instead of deleting items.')),
                ('is_primary', models.BooleanField(default=False, help_text='Designates whether this item is the primary item. Only one active item should be marked as primary.')),
                ('name', models.CharField(help_text="Group name that groups related list items (e.g., 'Electronics', 'Furniture').", max_length=255)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=1, help_text='Display order (lower numbers - zero included - appear first)')),
                ('bootstrap_icon', models.CharField(blank=True, help_text="Optional Bootstrap icon class. Example: 'bi bi-cart' for a shopping cart icon. Find icons at [Bootstrap Icons](https://icons.getbootstrap.com/).", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time last updated.')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this item should be treated as active. Unselect this instead of deleting items.')),
                ('is_primary', models.BooleanField(default=False, help_text='Designates whether this item is the primary item. Only one active item should be marked as primary.')),
                ('name', models.CharField(help_text='Name of the item.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of this item, including features or specifications (optional).')),
                ('groups', models.ManyToManyField(blank=True, help_text='Groups this item belongs to.', related_name='items', to='lists.group')),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'abstract': False,
            },
        ),
    ]
