"""Helpers for README.md generation."""

import builtins
import pathlib
from typing import Any, cast

from ..... import Package


def readme_header(project_name: str) -> list[str]:
    """File header lines."""
    return [
        f"# {project_name} {Package.DISPLAY_NAME} project",
        "",
        "## Quick Start",
        "",
        "- Install dependencies (e.g. `uv sync`).",
        f"- Run the development server (`uv run {Package.NAME} runserver`).",
        "- To configure the project, see the configuration section below.",
        "",
        "## Configuration",
        "",
        "Settings can be provided via three mechanisms, in order of precedence:",
        "",
        f"1. **Environment variable** — set in your `.env` file (e.g. `MY_VAR=value`)",
        f'2. **`pyproject.toml`** — set as a key under the `[tool.{Package.NAME}]` (e.g. `my_var = "value"`)',
        f"3. **Default** — the built-in fallback value used when nothing else is provided",
        "",
    ]


def readme_section_header(class_name: str) -> list[str]:
    """Section header for a config class."""
    return [f"### {class_name}", ""]


def readme_table_header() -> list[str]:
    """Markdown table header row."""
    return [
        "| Environment Variable | TOML Key | Accepted Values | Default |",
        "| -------------------- | -------- | --------------- | ------- |",
    ]


def readme_footer() -> list[str]:
    """File footer lines."""
    return [
        "---",
        "",
        f"> This file was generated by `{Package.NAME} generate readme`. Re-run the command to refresh it.",
    ]


def readme_format_choices(choices: list[str]) -> str:
    """Format choices as inline code alternatives."""
    return " \\| ".join(f"`{choice}`" for choice in choices)


def readme_get_type_hint(field_type: type) -> str:
    """Return a human-readable type hint for a field type."""
    match field_type:
        case builtins.bool:
            return "`true` \\| `false`"
        case builtins.int:
            return "integer"
        case builtins.float:
            return "float"
        case builtins.list:
            return "comma-separated values"
        case pathlib.Path:
            return "absolute path"
        case _:
            pass
    return "string"


def readme_format_default_value(value: Any, field_type: type) -> str:
    """Format a default value for display in a markdown table cell."""
    if value is None:
        return "*(none)*"

    match field_type:
        case builtins.bool:
            return f"`{'true' if value else 'false'}`"
        case builtins.list:
            if isinstance(value, list):
                list_items = cast(list[Any], value)
                if not list_items:
                    return "*(empty)*"
                return f"`{','.join(str(v) for v in list_items)}`"
            return f"`{value}`"
        case pathlib.Path:
            return f"`{pathlib.PurePosixPath(value)}`"
        case _:
            pass
    return f"`{value}`"


def readme_table_row(
    env_var: str, toml_key: str | None, choices_key: list[str] | None, default_value: Any, field_type: type
) -> str:
    """Format a single markdown table row for a config field."""
    env_cell = f"`{env_var}`"
    toml_cell = f"`{toml_key}`" if toml_key else "—"
    values_cell = readme_format_choices(choices_key) if choices_key else readme_get_type_hint(field_type)
    default_cell = readme_format_default_value(default_value, field_type)
    return f"| {env_cell} | {toml_cell} | {values_cell} | {default_cell} |"
